In [1]:
import urllib.request
import json
from pandas import json_normalize
from urllib.parse import urlencode, quote_plus, unquote
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import requests

In [2]:
observatory = ['TW_0088', 'TW_0089', 'TW_0095', 'TW_0091', 'KG_0025', 'TW_0069', 'KG_0024', 'TW_0094', 'TW_0079', 'TW_0081', 'TW_0093', 'TW_0090', 'TW_0080','KG_0102',
'KG_0101', 'TW_0092', 'KG_0021', 'KG_0028','TW_0075', 'HB_0002', 'HB_0001', 'HB_0009', 'HB_0008', 'HB_0007', 'TW_0062']

In [3]:
df = pd.DataFrame(columns=['obs_post_id', 'obs_post_name', 'record_time', 'lat', 'lon', 'current_direct', 'current_speed', 'obs_last_req_cnt'])

In [ ]:
import pandas as pd

# API 요청에 필요한 매개변수 설정
service_key = 'n3d6UzSXMhKEN5Vcwa6wKw=='
obs_code = observatory
search_date = '20180504'

# 빈 데이터프레임 생성
df = pd.DataFrame()

# API 요청 URL 생성 및 데이터 처리
for i in range(len(obs_code)):
    url = f"http://www.khoa.go.kr/api/oceangrid/tidalHfRadar/search.do?ServiceKey={service_key}&ObsCode={obs_code[i]}&Date={search_date}&ResultType=json"

    try:
        # API 요청 보내기
        with urllib.request.urlopen(url) as response:
            data = response.read().decode('utf-8')

        # JSON 데이터 파싱
        json_data = json.loads(data)

        # 예시로 응답 데이터 출력
        df = df.append(pd.DataFrame(json_data))

    except urllib.error.HTTPError as e:
        # API 요청 중 오류 발생 시 처리
        print(f"HTTP Error: {e.code}, {e.reason}")

# 데이터프레임 출력
print(df)

In [ ]:
import requests
import pandas as pd

# API 호출을 위한 URL과 변수 설정
service_key = 'n3d6UzSXMhKEN5Vcwa6wKw=='
obs_code = 'HF_0041'
search_date = '2016010101'

# # API 호출 및 데이터 가져오기
# http://www.khoa.go.kr/api/oceangrid/tidalHfRadar/search.do?ServiceKey=wldhxng34hkddbsgm81lwldhxng34hkddbsgm81l==&ObsCode=HF_0041&Date=2016010101&ResultType=json
api_url = f"http://www.khoa.go.kr/api/oceangrid/tidalHfRadar/search.do?ServiceKey={service_key}&ObsCode={obs_code}&Date={search_date}&ResultType=json"
# response = requests.get(api_url)
# data = response.json()

# # 필요한 항목 추출
# item_list = data['result']['data']
# columns = ['lon', 'current_direct', 'current_speed', 'lat']
# rows = [[item[column] for column in columns] for item in item_list]

# # 데이터프레임 생성
# df = pd.DataFrame(rows, columns=columns)
# df.head()

In [12]:
# 날짜 생성하기
import pandas as pd
rct3 = pd.date_range(start='20200228', end='20201231')
dt_list = rct3.strftime("%Y%m%d").to_list()

print(dt_list)

['20200228', '20200229', '20200301', '20200302', '20200303', '20200304', '20200305', '20200306', '20200307', '20200308', '20200309', '20200310', '20200311', '20200312', '20200313', '20200314', '20200315', '20200316', '20200317', '20200318', '20200319', '20200320', '20200321', '20200322', '20200323', '20200324', '20200325', '20200326', '20200327', '20200328', '20200329', '20200330', '20200331', '20200401', '20200402', '20200403', '20200404', '20200405', '20200406', '20200407', '20200408', '20200409', '20200410', '20200411', '20200412', '20200413', '20200414', '20200415', '20200416', '20200417', '20200418', '20200419', '20200420', '20200421', '20200422', '20200423', '20200424', '20200425', '20200426', '20200427', '20200428', '20200429', '20200430', '20200501', '20200502', '20200503', '20200504', '20200505', '20200506', '20200507', '20200508', '20200509', '20200510', '20200511', '20200512', '20200513', '20200514', '20200515', '20200516', '20200517', '20200518', '20200519', '20200520', '20200521', '20200522', '20200523', '20200524', '20200525', '20200526', '20200527', '20200528', '20200529', '20200530', '20200531', '20200601', '20200602', '20200603', '20200604', '20200605', '20200606', '20200607', '20200608', '20200609', '20200610', '20200611', '20200612', '20200613', '20200614', '20200615', '20200616', '20200617', '20200618', '20200619', '20200620', '20200621', '20200622', '20200623', '20200624', '20200625', '20200626', '20200627', '20200628', '20200629', '20200630', '20200701', '20200702', '20200703', '20200704', '20200705', '20200706', '20200707', '20200708', '20200709', '20200710', '20200711', '20200712', '20200713', '20200714', '20200715', '20200716', '20200717', '20200718', '20200719', '20200720', '20200721', '20200722', '20200723', '20200724', '20200725', '20200726', '20200727', '20200728', '20200729', '20200730', '20200731', '20200801', '20200802', '20200803', '20200804', '20200805', '20200806', '20200807', '20200808', '20200809', '20200810', '20200811', '20200812', '20200813', '20200814', '20200815', '20200816', '20200817', '20200818', '20200819', '20200820', '20200821', '20200822', '20200823', '20200824', '20200825', '20200826', '20200827', '20200828', '20200829', '20200830', '20200831', '20200901', '20200902', '20200903', '20200904', '20200905', '20200906', '20200907', '20200908', '20200909', '20200910', '20200911', '20200912', '20200913', '20200914', '20200915', '20200916', '20200917', '20200918', '20200919', '20200920', '20200921', '20200922', '20200923', '20200924', '20200925', '20200926', '20200927', '20200928', '20200929', '20200930', '20201001', '20201002', '20201003', '20201004', '20201005', '20201006', '20201007', '20201008', '20201009', '20201010', '20201011', '20201012', '20201013', '20201014', '20201015', '20201016', '20201017', '20201018', '20201019', '20201020', '20201021', '20201022', '20201023', '20201024', '20201025', '20201026', '20201027', '20201028', '20201029', '20201030', '20201031', '20201101', '20201102', '20201103', '20201104', '20201105', '20201106', '20201107', '20201108', '20201109', '20201110', '20201111', '20201112', '20201113', '20201114', '20201115', '20201116', '20201117', '20201118', '20201119', '20201120', '20201121', '20201122', '20201123', '20201124', '20201125', '20201126', '20201127', '20201128', '20201129', '20201130', '20201201', '20201202', '20201203', '20201204', '20201205', '20201206', '20201207', '20201208', '20201209', '20201210', '20201211', '20201212', '20201213', '20201214', '20201215', '20201216', '20201217', '20201218', '20201219', '20201220', '20201221', '20201222', '20201223', '20201224', '20201225', '20201226', '20201227', '20201228', '20201229', '20201230', '20201231']

In [ ]:
from urllib.request import Request, urlopen
from urllib.parse import urlencode, unquote
import pandas as pd
from pandas import json_normalize
import json
import datetime
from collections import defaultdict
servicekey = 'n3d6UzSXMhKEN5Vcwa6wKw=='

resulttype = 'json'
tide = []
columns = ['date', 'obs', 'current_speed']

for datetime in dt_list:
    date = f'{datetime}'
    print('next date')
    for obs in observatory:
        obscode = f'{obs}'

        url = "http://www.khoa.go.kr/api/oceangrid/tidalBu/search.do?"
        queryString = '&' + urlencode({'ServiceKey':unquote(servicekey),
                                                    'ObsCode':obscode,
                                                    'Date':date,
                                                    'ResultType':resulttype})

        queryURL = url + queryString
        response = urlopen(queryURL)
        json_api = response.read()
        json_file = json.loads(json_api)

        sum = 0
        try:
            for i in json_file['result']['data']:
                sum += float(i['current_speed'])
                avg = round(sum / len(json_file['result']['data']), 3)
            display(avg)
            li = [datetime, obs, avg]

            senten = pd.DataFrame([li], columns = columns)
            if obs == 'TW_0088':
                td = pd.DataFrame([li], columns = columns)
        except KeyError:
            print(None)

            li = [datetime, obs, 'None']
            senten = pd.DataFrame([li], columns = columns)
            if obs == 'TW_0088':
                td = pd.DataFrame([li], columns = columns)
        td = pd.concat([td, senten], axis = 0)
        td.reset_index(drop = True, inplace = True)
    if date == '20200228':
        ws_data_20200228 = td.copy()
    df = td.copy()
    ws_data_20200228 = pd.concat([ws_data_20200228, df])

In [14]:
ws_data_20200228

        date      obs current_speed
0   20200228  TW_0088         4.626
1   20200228  TW_0088         4.626
2   20200228  TW_0089        53.507
3   20200228  TW_0095          None
4   20200228  TW_0091         5.545
..       ...      ...           ...
21  20201231  HB_0001        20.987
22  20201231  HB_0009         9.309
23  20201231  HB_0008        11.213
24  20201231  HB_0007         6.479
25  20201231  TW_0062        21.423

[8034 rows x 3 columns]

In [15]:
ws_data_20200228.reset_index(drop=True, inplace=True)

In [16]:
ws_data_20200228.to_csv('/content/drive/MyDrive/Colab Notebooks/BigProject/ws_data_2020_2.csv')